---
output: pdf_document
---

\center Table : Dataset Information for PJM \center

|  **Detail**   | **Description **                                           | 
|:--------------|------------------------------------------------------------|
|Data Source:   |JM Website - Metered Hourly Load                            |  
|Retrieved From:|https://dataminer2.pjm.com/feed/hrl_load_metered/definition | 
|Variables Used:|datetime_beginning_ept(Date), mw (Load_MW)                  | 
|Date Range:    |1/1/2010 - 12/31/2022                                       | 



\center Table : Real-Time Dataset Information for PJM \center 

|  **Detail**   | **Description **                                               | 
|:--------------|----------------------------------------------------------------|
|Data Source:   |PJM website - Regulation Zone Preliminary Billing Data          | 
|Retrieved From:|https://dataminer2.pjm.com/feed/reg_zone_prelim_bill/definition | 
|Variables Used:|datetime_beginning_ept(Date), mw (Load_MW), rmpcp (Price)       | 
|Date Range:    |1/1/2013 - 12/31/2022                                           | 



\center Table : Day-Ahead Dataset Information for PJM \center 

|  **Detail**   | **Description **                                           | 
|:--------------|------------------------------------------------------------|
|Data Source:   |PJM website - Day-Ahead Scheduling Reserve                  | 
|Retrieved From:|https://dataminer2.pjm.com/feed/dasr_results/definition     | 
|Variables Used:|datetime_beginning_ept (Date), mw (Load_MW), dasrmcp (Price)| 
|Date Range:    |1/1/2010 - 12/31/2022                                       | 



\center Table : Dataset Information for ERCOT \center 

|  **Detail**   | **Description **                                           | 
|:--------------|------------------------------------------------------------|
|Data Source:   |ERCOT Hourly Load Data Archives                             | 
|Retrieved From:|https://www.ercot.com/gridinfo/load/load_hist               | 
|Variables Used:|Hour_Ending, ERCOT                                          | 
|Date Range:    | 1/1/2010 - 12/31/2022                                      | 



\center Table : ERCOT Linear Model Demographic Data \center 

| **Detail**       | **Description **                                | 
|:--------------   |-------------------------------------------------|
|Year:             | 2010 - 2022                                     | 
|Electricity Price:|Average prices of electricity to ultimate customers         (https://www.eia.gov/totalenergy/data/monthly/pdf/sec9_11.pdf)       | 
|Median Income:    | Income level at which half of the households in Texas earn more and half earn less  (https://fred.stlouisfed.org/series/MEHOINUSTXA672N# )    |                      
|Percent Renewable:|                                                 | 
|Percent Minority: | Subtraction of white only percentages after dividing white popultion from totals (U.S. Census 2010-2022)                                  |
|Population:       | Total Population each year for Texas         (https://www.census.gov/programs-surveys/popest/data/data-sets.html) |
|Mean Load:        | Average load for ERCOT                          |







